apiVersion: v1
kind: Service
metadata:
  name: webserver-service
  labels: 
    app: webserver-service
spec:
  type: LoadBalancer
  ports: 
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: webserver-deployment
  sessionAffinity: None