apiVersion: apps/v1
kind: Deployment
metadata:
  name: kmwebserver
spec:
  selector:
    matchLabels:
      app: web
  replicas: 2
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: kmwebserver-con
          image: 
          ports:
            - containerPort: 8000
